from pathlib import Path

from colosseum_sdk.config.robot import RobotCfg, register_robot

_HERE = Path(__file__).parent

JOINT_NAMES = [
    "AAHead_yaw",
    "Head_pitch",
    "Left_Shoulder_Pitch",
    "Left_Shoulder_Roll",
    "Left_Elbow_Pitch",
    "Left_Elbow_Yaw",
    "Right_Shoulder_Pitch",
    "Right_Shoulder_Roll",
    "Right_Elbow_Pitch",
    "Right_Elbow_Yaw",
    "Waist",
    "Left_Hip_Pitch",
    "Left_Hip_Roll",
    "Left_Hip_Yaw",
    "Left_Knee_Pitch",
    "Left_Ankle_Pitch",
    "Left_Ankle_Roll",
    "Right_Hip_Pitch",
    "Right_Hip_Roll",
    "Right_Hip_Yaw",
    "Right_Knee_Pitch",
    "Right_Ankle_Pitch",
    "Right_Ankle_Roll",
]


@register_robot("t1")
class T1RobotCfg(RobotCfg):
    def __init__(self) -> None:
        super().__init__(
            xml_path=_HERE / "t1.xml",
            joint_names=JOINT_NAMES,
            # Observation zero-point: obs[6:29] = joint_pos - default_joint_pos.
            default_joint_pos={
                "AAHead_yaw": 0.0,
                "Head_pitch": 0.0,
                "Left_Shoulder_Pitch": 0.25,
                "Left_Shoulder_Roll": -1.4,
                "Left_Elbow_Pitch": 0.0,
                "Left_Elbow_Yaw": -0.2,
                "Right_Shoulder_Pitch": 0.25,
                "Right_Shoulder_Roll": 1.4,
                "Right_Elbow_Pitch": 0.0,
                "Right_Elbow_Yaw": 0.2,
                "Waist": 0.0,
                "Left_Hip_Pitch": -0.38,
                "Left_Hip_Roll": 0.0,
                "Left_Hip_Yaw": 0.0,
                "Left_Knee_Pitch": 0.8,
                "Left_Ankle_Pitch": -0.43,
                "Left_Ankle_Roll": 0.0,
                "Right_Hip_Pitch": -0.38,
                "Right_Hip_Roll": 0.0,
                "Right_Hip_Yaw": 0.0,
                "Right_Knee_Pitch": 0.8,
                "Right_Ankle_Pitch": -0.43,
                "Right_Ankle_Roll": 0.0,
            },
            # PD stiffness (kp) — from arena T1VelocitySymmetric.cpp joint_stiffness.
            joint_stiffness={
                "AAHead_yaw": 5.0,
                "Head_pitch": 5.0,
                "Left_Shoulder_Pitch": 50.0,
                "Left_Shoulder_Roll": 50.0,
                "Left_Elbow_Pitch": 50.0,
                "Left_Elbow_Yaw": 50.0,
                "Right_Shoulder_Pitch": 50.0,
                "Right_Shoulder_Roll": 50.0,
                "Right_Elbow_Pitch": 50.0,
                "Right_Elbow_Yaw": 50.0,
                "Waist": 150.0,
                "Left_Hip_Pitch": 200.0,
                "Left_Hip_Roll": 200.0,
                "Left_Hip_Yaw": 200.0,
                "Left_Knee_Pitch": 200.0,
                "Left_Ankle_Pitch": 50.0,
                "Left_Ankle_Roll": 50.0,
                "Right_Hip_Pitch": 200.0,
                "Right_Hip_Roll": 200.0,
                "Right_Hip_Yaw": 200.0,
                "Right_Knee_Pitch": 200.0,
                "Right_Ankle_Pitch": 50.0,
                "Right_Ankle_Roll": 50.0,
            },
            # PD damping (kd) — from arena T1VelocitySymmetric.cpp joint_damping.
            joint_damping={
                "AAHead_yaw": 1.5,
                "Head_pitch": 1.5,
                "Left_Shoulder_Pitch": 1.0,
                "Left_Shoulder_Roll": 1.0,
                "Left_Elbow_Pitch": 1.0,
                "Left_Elbow_Yaw": 1.0,
                "Right_Shoulder_Pitch": 1.0,
                "Right_Shoulder_Roll": 1.0,
                "Right_Elbow_Pitch": 1.0,
                "Right_Elbow_Yaw": 1.0,
                "Waist": 5.0,
                "Left_Hip_Pitch": 5.0,
                "Left_Hip_Roll": 5.0,
                "Left_Hip_Yaw": 5.0,
                "Left_Knee_Pitch": 5.0,
                "Left_Ankle_Pitch": 3.0,
                "Left_Ankle_Roll": 3.0,
                "Right_Hip_Pitch": 5.0,
                "Right_Hip_Roll": 5.0,
                "Right_Hip_Yaw": 5.0,
                "Right_Knee_Pitch": 5.0,
                "Right_Ankle_Pitch": 3.0,
                "Right_Ankle_Roll": 3.0,
            },
            # Torque limits (N·m) — from arena T1VelocitySymmetric.cpp effort_limit.
            effort_limit={
                "AAHead_yaw": 7.0,
                "Head_pitch": 7.0,
                "Left_Shoulder_Pitch": 30.0,
                "Left_Shoulder_Roll": 30.0,
                "Left_Elbow_Pitch": 30.0,
                "Left_Elbow_Yaw": 30.0,
                "Right_Shoulder_Pitch": 30.0,
                "Right_Shoulder_Roll": 30.0,
                "Right_Elbow_Pitch": 30.0,
                "Right_Elbow_Yaw": 30.0,
                "Waist": 40.0,
                "Left_Hip_Pitch": 90.0,
                "Left_Hip_Roll": 40.0,
                "Left_Hip_Yaw": 40.0,
                "Left_Knee_Pitch": 118.0,
                "Left_Ankle_Pitch": 57.0,
                "Left_Ankle_Roll": 57.0,
                "Right_Hip_Pitch": 90.0,
                "Right_Hip_Roll": 40.0,
                "Right_Hip_Yaw": 40.0,
                "Right_Knee_Pitch": 118.0,
                "Right_Ankle_Pitch": 57.0,
                "Right_Ankle_Roll": 57.0,
            },
            # Uniform reflected inertia — arena uses joint_armature.fill(0.3f).
            joint_armature={".*": 0.3},
            # Coulomb friction — ankles use a smaller motor (0.1), everything else 0.2.
            joint_frictionloss={
                ".*Ankle.*": 0.1,
                ".*": 0.2,
            },
            skill_models={
                "locomotion": _HERE / "models" / "locomotion.onnx",
            },
        )
